-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-10-30 23:05:17 CST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Inv 
    ( 
     ID_Inv            INTEGER  NOT NULL , 
     Nombre_inventario VARCHAR2 (150)  NOT NULL , 
     Categoria         VARCHAR2 (50)  NOT NULL , 
     Unidad_ID_Unidad  INTEGER  NOT NULL , 
     Stock_actual      NUMBER (10,2)  NOT NULL , 
     Costo_unitario    NUMBER (10,2)  NOT NULL , 
     Stock_minimo      NUMBER (10,2) , 
     Proveedor         VARCHAR2 (100) 
    ) 
;

ALTER TABLE Inv 
    ADD CONSTRAINT Inv_PK PRIMARY KEY ( ID_Inv ) ;

CREATE TABLE Mov_Inventario 
    ( 
     ID_Mov            INTEGER  NOT NULL , 
     Inv_ID_Inv        INTEGER  NOT NULL , 
     Pedidos_ID_Pedido INTEGER  NOT NULL , 
     Tipo              VARCHAR2 (20)  NOT NULL , 
     Cantidad          NUMBER (10,2)  NOT NULL , 
     Costo             NUMBER (10,2)  NOT NULL , 
     Fecha             DATE  NOT NULL , 
     Razon             VARCHAR2 (150) 
    ) 
;

ALTER TABLE Mov_Inventario 
    ADD CONSTRAINT Mov_Inventario_PK PRIMARY KEY ( ID_Mov ) ;

CREATE TABLE Pedidos 
    ( 
     ID_Pedido           INTEGER  NOT NULL , 
     Usuarios_ID_Usuario INTEGER  NOT NULL , 
     Precio_total        NUMBER (10,2)  NOT NULL , 
     Estado              VARCHAR2 (20)  NOT NULL , 
     Fecha_pedido        DATE  NOT NULL , 
     Fecha_entrega       DATE  NOT NULL , 
     Notas               VARCHAR2 (250) 
    ) 
;

ALTER TABLE Pedidos 
    ADD CONSTRAINT Pedidos_PK PRIMARY KEY ( ID_Pedido ) ;

CREATE TABLE Prod_Ingred 
    ( 
     ID_PI                 INTEGER  NOT NULL , 
     Productos_ID_Producto INTEGER  NOT NULL , 
     Inv_ID_Inv            INTEGER  NOT NULL , 
     Cantidad              NUMBER (10,4)  NOT NULL , 
     Unidad_ID_Unidad      INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Prod_Ingred 
    ADD CONSTRAINT Prod_Ingred_PK PRIMARY KEY ( ID_PI ) ;

CREATE TABLE Productos 
    ( 
     ID_Producto     INTEGER  NOT NULL , 
     Nombre_producto VARCHAR2 (150)  NOT NULL , 
     Tipo_producto   VARCHAR2 (20)  NOT NULL , 
     Precio_base     NUMBER (10,2)  NOT NULL , 
     Personalizable  CHAR (1)  NOT NULL , 
     Atributos       CLOB , 
     Disponible      CHAR (1) , 
     Imagen          BLOB 
    ) 
;

ALTER TABLE Productos 
    ADD CONSTRAINT Productos_PK PRIMARY KEY ( ID_Producto ) ;

CREATE TABLE Productos_Pedido 
    ( 
     ID_producto_pedido    INTEGER  NOT NULL , 
     Pedidos_ID_Pedido     INTEGER  NOT NULL , 
     Productos_ID_Producto INTEGER  NOT NULL , 
     Cantidad              INTEGER  NOT NULL , 
     Precio_unitario       NUMBER (10,2)  NOT NULL , 
     Personalizaciones     CLOB 
    ) 
;

ALTER TABLE Productos_Pedido 
    ADD CONSTRAINT Productos_Pedido_PK PRIMARY KEY ( ID_producto_pedido ) ;

CREATE TABLE Unidad 
    ( 
     ID_Unidad     INTEGER  NOT NULL , 
     Nombre_unidad VARCHAR2 (20)  NOT NULL , 
     Abreviacion   VARCHAR2 (10)  NOT NULL 
    ) 
;

ALTER TABLE Unidad 
    ADD CONSTRAINT Unidad_PK PRIMARY KEY ( ID_Unidad ) ;

CREATE TABLE Usuarios 
    ( 
     ID_Usuario        INTEGER  NOT NULL , 
     Nombre_usuario    VARCHAR2 (150)  NOT NULL , 
     Correo_usuario    VARCHAR2 (150)  NOT NULL , 
     Hash_contraseña   VARCHAR2 (255)  NOT NULL , 
     Telefono_usuario  VARCHAR2 (20)  NOT NULL , 
     Direccion_usuario VARCHAR2 (150)  NOT NULL , 
     Rol               VARCHAR2 (20)  NOT NULL , 
     Fecha_creacion    DATE  NOT NULL , 
     Imagen            BLOB 
    ) 
;

ALTER TABLE Usuarios 
    ADD CONSTRAINT Usuarios_PK PRIMARY KEY ( ID_Usuario ) ;

ALTER TABLE Inv 
    ADD CONSTRAINT Inv_Unidad_FK FOREIGN KEY 
    ( 
     Unidad_ID_Unidad
    ) 
    REFERENCES Unidad 
    ( 
     ID_Unidad
    ) 
;

ALTER TABLE Mov_Inventario 
    ADD CONSTRAINT Mov_Inventario_Inv_FK FOREIGN KEY 
    ( 
     Inv_ID_Inv
    ) 
    REFERENCES Inv 
    ( 
     ID_Inv
    ) 
;

ALTER TABLE Mov_Inventario 
    ADD CONSTRAINT Mov_Inventario_Pedidos_FK FOREIGN KEY 
    ( 
     Pedidos_ID_Pedido
    ) 
    REFERENCES Pedidos 
    ( 
     ID_Pedido
    ) 
;

ALTER TABLE Pedidos 
    ADD CONSTRAINT Pedidos_Usuarios_FK FOREIGN KEY 
    ( 
     Usuarios_ID_Usuario
    ) 
    REFERENCES Usuarios 
    ( 
     ID_Usuario
    ) 
;

ALTER TABLE Prod_Ingred 
    ADD CONSTRAINT Prod_Ingred_Inv_FK FOREIGN KEY 
    ( 
     Inv_ID_Inv
    ) 
    REFERENCES Inv 
    ( 
     ID_Inv
    ) 
;

ALTER TABLE Prod_Ingred 
    ADD CONSTRAINT Prod_Ingred_Productos_FK FOREIGN KEY 
    ( 
     Productos_ID_Producto
    ) 
    REFERENCES Productos 
    ( 
     ID_Producto
    ) 
;

ALTER TABLE Prod_Ingred 
    ADD CONSTRAINT Prod_Ingred_Unidad_FK FOREIGN KEY 
    ( 
     Unidad_ID_Unidad
    ) 
    REFERENCES Unidad 
    ( 
     ID_Unidad
    ) 
;

ALTER TABLE Productos_Pedido 
    ADD CONSTRAINT Productos_Pedido_Pedidos_FK FOREIGN KEY 
    ( 
     Pedidos_ID_Pedido
    ) 
    REFERENCES Pedidos 
    ( 
     ID_Pedido
    ) 
;

ALTER TABLE Productos_Pedido 
    ADD CONSTRAINT Productos_Pedido_Productos_FK FOREIGN KEY 
    ( 
     Productos_ID_Producto
    ) 
    REFERENCES Productos 
    ( 
     ID_Producto
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             0
-- ALTER TABLE                             17
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
